# Generated by Django 2.1.3 on 2019-01-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField(max_length=4)),
                ('fabricante', models.CharField(max_length=50)),
            ],
        ),
    ]
